development:
  country_CL: "CL"
  country_MX: "MX"
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "INTEGRACION"
  webpay_logger: "webpay_development.log"
  BASE_APP: "localhost:3000"
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  miele_core_api:
    token: wbBsf6O6fpJBvFschcsvUAtt
    url_base: http://localhost:8000
  miele_ticket_api:
    token: kdOQrQZ1tQr2C0DXBYj3kAtt #staging cambiar a local
    url_base: http://localhost:9000 #staging http://localhost:8000 #
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
  miele_b2c_api:
    token: MtFxtzJWRQvAboHnLfPuDwtt #staging cambiar a local
    url_base: https://mieleb2c.garagelabs.cl #staging http://localhost:8000 #

test:
  country_CL: "CL"
  country_MX: "MX"
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "INTEGRACION"
  webpay_logger: "webpay_development.log"
  BASE_APP: "localhost:3000"
  mailer_user: "oferus.recovery@gmail.com"
  mailer_password: "oferusdev"
  miele_core_api:
    token: wbBsf6O6fpJBvFschcsvUAtt
    url_base: https://mielecore.garagelabs.cl
  miele_ticket_api:
    token: kdOQrQZ1tQr2C0DXBYj3kAtt #staging
    url_base: https://mieletickets.garagelabs.cl #staging
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
  miele_b2c_api:
    token: MtFxtzJWRQvAboHnLfPuDwtt
    url_base: https://mieleb2c.garagelabs.cl/

staging:
  country_CL: "CL"
  country_MX: "MX"
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "INTEGRACION"
  webpay_logger: "webpay_development.log"
  BASE_APP: "https://miele.garagelabs.cl"
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  miele_core_api:
    token: wbBsf6O6fpJBvFschcsvUAtt
    url_base: https://mielecore.garagelabs.cl
  miele_ticket_api:
    token: kdOQrQZ1tQr2C0DXBYj3kAtt #staging
    url_base: https://mieletickets.garagelabs.cl #staging
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
  miele_b2c_api:
    token: MtFxtzJWRQvAboHnLfPuDwtt
    url_base: https://mieleb2c.garagelabs.cl/

preproduction:
  country_CL: "CL"
  country_MX: "MX"
  webpay_wsdl: https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_develop.crt
  webpay_client_private_key: config/private_key_develop.key
  webpay_tbk_certificate: config/tbk_develop.key
  webpay_commerce_code: "597020000540"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "INTEGRACION"
  webpay_logger: "webpay_development.log"
  BASE_APP: "http://preprod.miele.garagelabs.cl"
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  miele_core_api:
    token: wbBsf6O6fpJBvFschcsvUAtt
    url_base: https://mielecore.garagelabs.cl
  miele_ticket_api:
    token: kdOQrQZ1tQr2C0DXBYj3kAtt
    url_base: https://mieletickets.garagelabs.cl
  webpay:
    key_id: "597055555532"
    key_secret: "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
  miele_b2c_api:
    token: MtFxtzJWRQvAboHnLfPuDwtt
    url_base: https://mieleb2c.garagelabs.cl/

# preproduction:
#   country_CL: "CL"
#   country_MX: "MX"
#   webpay_wsdl:  https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
#   webpay_client_certificate: config/public_cert_develop.crt
#   webpay_client_private_key: config/private_key_develop.key
#   webpay_tbk_certificate: config/tbk_develop.key
#   webpay_commerce_code: '597020000540'
#   webpay_return_url: /webpay/webpay_return_url
#   webpay_final_url: /webpay/webpay_final_url
#   webpay_ambient: 'INTEGRACION'
#   webpay_logger: 'webpay_development.log'
#   BASE_APP: 'http://preprod.miele.garagelabs.cl'
#   mail_admin: AKIAQKX5DXSE35FBB7HF
#   pass_admin: BDVEDYF3uq27kR+tX+BwPcKdoDV5Vpr//M2sC6n1vcRs
#   miele_core_api:
#     token: wbBsf6O6fpJBvFschcsvUAtt
#     url_base: https://mielecore.garagelabs.cl
#   miele_ticket_api:
#     token: kdOQrQZ1tQr2C0DXBYj3kAtt    #staging
#     url_base: https://mieletickets.garagelabs.cl #staging
#   webpay:
#     key_id: '597055555532'
#     key_secret: '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'

production:
  country_CL: "CL"
  country_MX: "MX"
  webpay_wsdl: https://webpay3g.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/public_cert_production.crt
  webpay_client_private_key: config/private_key_production.key
  webpay_tbk_certificate: config/tbk_production.key
  webpay_commerce_code: "597035353135"
  webpay_return_url: /webpay/webpay_return_url
  webpay_final_url: /webpay/webpay_final_url
  webpay_ambient: "PRODUCCION"
  webpay_logger: "webpay_development.log"
  BASE_APP: "https://www.mielecustomers.cl"
  mailer_user: no-reply@miele.cl
  mailer_password: BFgUQc8owQfjbVnfcOhU0bM9Qi+YQbw2ak3hb5iOkbM9
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
  miele_core_api:
    token: quard7eXXnXllrJ7QQsZbwtt
    url_base: https://core.mielecustomers.cl
  miele_ticket_api:
    token: uTVCZJjRxIJYkz9FaS50Rgtt
    url_base: https://tickets.mielecustomers.cl
  webpay:
    key_id: "597035353135"
    key_secret: "9e4a1ac1ce7add97df44d8c5104a733f"
  miele_b2c_api:
    token: tIPIKOzKyzLCQJzFSVzjdgtt
    url_base: https://shop.miele.cl
