# CREANDO ROLES DE USUARIO
begin
  Role.create!(id: 1, name: "Administrador")
  Role.create!(id: 2, name: 'Manager')
  Role.create!(id: 3, name: 'Seller')
  Role.create!(id: 5, name: 'Consultivo')
  Role.create!(id: 6, name: 'Finanzas')
  Role.create!(id: 7, name: 'Manager Finanzas')
  Role.create!(id: 8, name: 'Despacho')
  Role.create!(id: 9, name: 'Manager Despacho')
  Role.create!(id: 10, name: 'Instalación')
  Role.create!(id: 11, name: 'Manager Instalación')
  Role.create!(id: 12, name: 'Manager Inventario')
  ActiveRecord::Base.connection.execute("SELECT setval('roles_id_seq', (SELECT max(id) FROM roles))")
  puts 'Roles creados con éxito!'
rescue Exception => e
  puts 'WARNING: Falló la carga de roles X.X'
end

# CREANDO USUARIOS DE PRUEBA
begin
  # Usuario Administrador
  User.create!(email: 'oferusat@gmail.com', password: "oferusdev", name: "Administrador", role_id: 1, lastname: 'Test', second_lastname: 'Miele', shop: 'Vitacura', phone: '987654321', workday: 'Full Time')
  puts 'Usuarios creados con éxito!'
rescue Exception => e
  puts 'WARNING: Falló la carga de usuarios X.X'
end

# CREANDO CANALES DE VENTA
begin
  SaleChannel.create!(name: 'MCA'              , id: 1, color: '#F59B00')
  SaleChannel.create!(name: 'Proyectos'        , id: 2, color: '#FDC568')
  SaleChannel.create!(name: 'Own Retail'       , id: 3, color: '#8C0314')
  SaleChannel.create!(name: 'Retail'           , id: 4, color: '#FD9184')
  SaleChannel.create!(name: 'E-commerce'       , id: 5, color: '#D5423D')
  puts 'Canales de venta creados con éxito!'
rescue Exception => e
  puts 'WARNING: Falló la carga de canales de venta X.X'
end

begin
  Region.create(id: 1,name: "Región de Tarapacá") #"Región de Tarapacá"
  Region.create(id: 2,name: "Región de Antofagasta")# "Región de Antofagasta"
  Region.create(id: 3,name: "Región de Atacama") #"Región de Atacama"
  Region.create(id: 4,name: "Región de Coquimbo") #"Región de Coquimbo"
  Region.create(id: 5,name: "Región de Valparaíso")#"Región de Valparaíso"
  Region.create(id: 6,name: "Región de O'Higgins") #"Región del Libertador General Bernardo O’Higgins"
  Region.create(id: 7,name: "Región del Maule") #"Región del Maule"
  Region.create(id: 8,name: "Región del Biobío") #"Región del Biobío"
  Region.create(id: 9,name: "Región de La Araucanía")# "Región de la Araucanía"
  Region.create(id: 10,name: "Región de Los Lagos") #"Región de los Lagos"
  Region.create(id: 11,name: "Región de Aysén") #"Región Aysén"
  Region.create(id: 12,name: "Región de Magallanes") #"Región de Magallanes y Antártica Chilena"
  Region.create(id: 13,name: "Región Metropolitana") #"Región Metropolitana"
  Region.create(id: 14,name: "Región de Los Ríos") #"Región de los Ríos"
  Region.create(id: 15,name: "Región de Arica y Parinacota") #"Región de Arica y Parinacota"
  Region.create(id: 16,name: "Región de Ñuble") #"Región del Biobío"
rescue
  puts 'WARNING: Falló la carga de Region X.X'
end

begin
  region = Region.find_or_create_by(id: 1,name: "Región de Tarapacá") #"Región de Tarapacá"
  region.update(mda_a: 89900, mda_b: 84900, mda_c: 79900, sda_a: 22900, sda_b: 19900, sda_c: 16900, pai_a: 22900)
  region = Region.find_or_create_by(id: 2,name: "Región de Antofagasta")# "Región de Antofagasta"
  region.update(mda_a: 59900, mda_b: 54900, mda_c: 49900, sda_a: 19900, sda_b: 16900, sda_c: 13900, pai_a: 19900)
  region = Region.find_or_create_by(id: 3,name: "Región de Atacama") #"Región de Atacama"
  region.update(mda_a: 89900, mda_b: 84900, mda_c: 79900, sda_a: 22900, sda_b: 19900, sda_c: 16900, pai_a: 22900)
  region = Region.find_or_create_by(id: 4,name: "Región de Coquimbo") #"Región de Coquimbo"
  region.update(mda_a: 49900, mda_b: 44900, mda_c: 39900, sda_a: 15900, sda_b: 12900, sda_c: 9900, pai_a: 15900)
  region = Region.find_or_create_by(id: 5,name: "Región de Valparaíso")#"Región de Valparaíso"
  region.update(mda_a: 39900, mda_b: 34900, mda_c: 29900, sda_a: 9900, sda_b: 6900, sda_c: 3900, pai_a: 9900)
  region = Region.find_or_create_by(id: 6,name: "Región de O'Higgins") #"Región del Libertador General Bernardo O’Higgins"
  region.update(mda_a: 49900, mda_b: 44900, mda_c: 39900, sda_a: 9900, sda_b: 5900, sda_c: 3900, pai_a: 9900)
  region = Region.find_or_create_by(id: 7,name: "Región del Maule") #"Región del Maule"
  region.update(mda_a: 64900, mda_b: 59900, mda_c: 54900, sda_a: 19900, sda_b: 16900, sda_c: 13900, pai_a: 19900)
  region = Region.find_or_create_by(id: 8,name: "Región del Biobío") #"Región del Biobío"
  region.update(mda_a: 45900, mda_b: 40900, mda_c: 35900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
  region = Region.find_or_create_by(id: 9,name: "Región de La Araucanía")# "Región de la Araucanía"
  region.update(mda_a: 69900, mda_b: 64900, mda_c: 59900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
  region = Region.find_or_create_by(id: 10,name: "Región de Los Lagos") #"Región de los Lagos"
  region.update(mda_a: 64900, mda_b: 59900, mda_c: 54900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
  region = Region.find_or_create_by(id: 11,name: "Región de Aysén") #"Región Aysén"
  region.update(mda_a: 69900, mda_b: 54900, mda_c: 59900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
  region = Region.find_or_create_by(id: 12,name: "Región de Magallanes") #"Región de Magallanes y Antártica Chilena"
  region.update(mda_a: 69900, mda_b: 64900, mda_c: 59900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
  region = Region.find_or_create_by(id: 13,name: "Región Metropolitana") #"Región Metropolitana"
  region.update(mda_a: 19900, mda_b: 17900, mda_c: 15900, sda_a: 6900, sda_b: 5900, sda_c: 4900, pai_a: 6900)
  region = Region.find_or_create_by(id: 14,name: "Región de Los Ríos") #"Región de los Ríos"
  region.update(mda_a: 49900, mda_b: 44900, mda_c: 39900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
  region = Region.find_or_create_by(id: 15,name: "Región de Arica y Parinacota") #"Región de Arica y Parinacota"
  region.update(mda_a: 69900, mda_b: 64900, mda_c: 59900, sda_a: 19900, sda_b: 16900, sda_c: 13900, pai_a: 19900)
  region = Region.find_or_create_by(id: 16,name: "Región de Ñuble") #"Región del Biobío"
  region.update(mda_a: 45900, mda_b: 40900, mda_c: 35900, sda_a: 14900, sda_b: 11900, sda_c: 8900, pai_a: 14900)
rescue
  puts 'WARNING: Falló la carga de despachos por Region'
end



begin
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Iquique")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Alto Hospicio")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Pozo Almonte")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Camina")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Colchane")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Huara")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Tarapacá").id , name: "Pica")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Antofagasta")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Mejillones")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Ollague")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Sierra Gorda")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Taltal")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Calama")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "San Pedro De Atacama")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "Tocopilla")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Antofagasta").id , name: "María Elena")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Copiapó")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Caldera")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Tierra Amarilla")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Chañaral")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Diego De Almagro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Vallenar")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Alto Del Carmen")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Freirina")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Atacama").id , name: "Huasco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "La Serena")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Coquimbo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Andacollo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "La Higuera")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Paiguano")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Vicuña")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Illapel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Canela")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Los Vilos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Salamanca")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Ovalle")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Combarbalá")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Monte Patria")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Punitaqui")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Coquimbo").id , name: "Río Hurtado")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Valparaíso")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Casablanca")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Concón")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Juan Fernández")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Puchuncaví")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Quintero")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Viña Del Mar")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Isla De Pascua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Los Andes")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Calle Larga")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Rinconada")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "San Esteban")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "La Ligua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Cabildo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Papudo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Petorca")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Zapallar")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Quillota")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Calera")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Hijuelas")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "La Cruz")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Nogales")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "San Antonio")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Algarrobo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Cartagena")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "El Quisco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "El Tabo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Santo Domingo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "San Felipe")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Catemu")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Llaillay")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Panquehue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Putaendo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Santa María")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Quilpue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Limache")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Olmué")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Valparaíso").id , name: "Villa Alemana")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Rancagua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Codegua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Coinco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Coltauco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Doñihue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Graneros")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Las Cabras")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Machalí")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Malloa")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Mostazal")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Olivar")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Peumo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Pichidegua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Quinta De Tilcoco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Rengo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Requinoa")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "San Vicente")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Pichilemu")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "La Estrella")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Litueche")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Marchihue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Navidad")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Paredones")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "San Fernando")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Chépica")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Chimbarongo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Lolol")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Nancagua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Palmilla")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Peralillo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Placilla")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Pumanque")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de O'Higgins").id , name: "Santa Cruz")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Talca")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Constitución")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Curepto")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Empedrado")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Maule")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Pelarco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Pencahue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Río Claro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "San Clemente")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "San Rafael")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Cauquenes")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Chanco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Pelluhue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Curicó")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Hualañé")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Licantén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Molina")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Rauco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Romeral")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Sagrada Familia")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Teno")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Vichuquén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Linares")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Colbún")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Longaví")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Parral")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Retiro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "San Javier")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Villa Alegre")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Maule").id , name: "Yerbas Buenas")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Concepción")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Coronel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Ranquil")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Niquén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Chiguayante")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Florida")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Hualqui")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Lota")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Penco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "San Pedro De La Paz")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Santa Juana")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Talcahuano")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Tomé")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Hualpén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Lebu")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Arauco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Canete")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Contulmo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Curanilahue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Los Alamos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Tirua")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Los Angeles")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Antuco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Cabrero")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Laja")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Mulchén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Nacimiento")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Negrete")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Quilaco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Quilleco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "San Rosendo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Santa Bárbara")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Tucapel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Yumbel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región del Biobío").id , name: "Alto Biobío")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Cobquecura")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Quirihue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Ninhue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Treguaco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Portezuelo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Coelemu")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "San Fabián")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "San Carlos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "San Nicolás")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Coihueco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Chillán")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Bulnes")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Chillán Viejo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "El Carmen")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Pemuco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Pinto")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Quillón")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "San Ignacio")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Ñuble").id , name: "Yungay")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Temuco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Carahue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Cunco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Curarrehue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Freire")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Galvarino")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Gorbea")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Lautaro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Loncoche")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Melipeuco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Nueva Imperial")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Padre Las Casas")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Perquenco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Pitrufquén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Pucón")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Saavedra")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Teodoro Schmidt")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Toltén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Vilcún")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Villarrica")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Chol Chol")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Angol")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Collipulli")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Curacautín")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Ercilla")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Lonquimay")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Los Sauces")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Lumaco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Purén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Renaico")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Traiguén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de La Araucanía").id , name: "Victoria")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Puerto Montt")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Calbuco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Cochamo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Fresia")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Frutillar")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Los Muermos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Llanquihue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Maullín")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Puerto Varas")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Castro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Ancud")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Chonchi")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Curaco De Vélez")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Dalcahue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Puqueldón")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Queilen")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Quellón")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Quemchi")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Quinchao")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Osorno")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Puerto Octay")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Purranque")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Puyehue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Río Negro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "San Juan De La Costa")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "San Pablo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Chaitén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Futaleufú")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Hualaihue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Lagos").id , name: "Palena")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Coyhaique")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Lago Verde")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Aysén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Cisnes")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Guaitecas")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Cochrane")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "O’Higgins")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Tortel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Chile Chico")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Aysén").id , name: "Río Ibanez")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Punta Arenas")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Laguna Blanca")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Río Verde")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "San Gregorio")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Cabo De Hornos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Antártica")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Porvenir")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Primavera")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Timaukel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Natales")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Magallanes").id , name: "Torres Del Paine")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Santiago")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Cerrillos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Cerro Navia")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Conchalí")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "El Bosque")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Estación Central")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Huechuraba")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Independencia")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "La Cisterna")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "La Florida")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "La Granja")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "La Pintana")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "La Reina")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Las Condes")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Lo Barnechea")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Lo Espejo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Lo Prado")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Macul")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Maipu")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Ñuñoa")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Pedro Aguirre Cerda")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Penalolén")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Providencia")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Pudahuel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Quilicura")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Quinta Normal")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Recoleta")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Renca")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "San Joaquín")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "San Miguel")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "San Ramón")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Vitacura")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Puente Alto")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Pirque")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "San Jose De Maipo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Colina")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Lampa")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Tiltil")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "San Bernardo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Buin")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Calera De Tango")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Paine")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Melipilla")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Alhue")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Curacaví")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "María Pinto")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "San Pedro")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Talagante")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "El Monte")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Isla De Maipo")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Padre Hurtado")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región Metropolitana").id , name: "Peñaflor")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Valdivia")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Corral")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Lanco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Los Lagos")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Mafil")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Mariquina")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Paillaco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Panguipulli")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "La Unión")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Futrono")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Lago Ranco")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Los Ríos").id , name: "Río Bueno")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Arica y Parinacota").id , name: "Arica")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Arica y Parinacota").id , name: "Camarones")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Arica y Parinacota").id , name: "Putre")
  Commune.find_or_create_by(region_id: Region.find_by(name: "Región de Arica y Parinacota").id , name: "General Lagos")
rescue
  puts 'WARNING: Falló la carga de Comunas X.X'
end

begin
  Family.create(id: 1, name: 'Cocción', depth: 0)
  Family.create(id: 2, name: 'Lavado', depth: 0)
  Family.create(id: 3, name: 'Lavavajillas', depth: 0)
  Family.create(id: 4, name: 'SDA', depth: 0)
  Family.create(id: 5, name: 'PAI', depth: 0)
  Family.create(id: 6, name: 'Servicios', depth: 0)
  Family.create(id: 7, name: 'Refrigeración', depth: 0)
  Family.create(name:'Sin categorizacion', depth: 0)
  ActiveRecord::Base.connection.execute("SELECT setval('families_id_seq', (SELECT max(id) FROM families))")
rescue Exception => e 
  puts 'WARNING: Business Units ya creados'
end

# CREANDO SERVICIOS
begin
  services = Family.find_by(name: 'Servicios', depth: 0)
  if !Product.find_by(name: 'Pre-visita (IVA incluido)')
    prod_t = Product.create!(name: "Pre-visita (IVA incluido)", sku: 'SERV01', price: '29900', stock: 10000, stock_break: true, mandatory: false, dispatch: true, instalation: true, description: 'Servicio', can_retire: true, built_in: false, outlet: false, product_type: '', profit_center: false)
    prod_t.families << services
    prod_t.sale_channels << SaleChannel.all
  end
  if !Product.find_by(name: 'Home Program')
    prod_t = Product.create!(name: "Home Program", sku: 'PEM', price: '99900', stock: 10000, description: 'Activación y puesta en marcha de productos Miele para mejorar la experiencia del usuario y poder aprovechar al máximo el potencial de cada producto', stock_break: true, mandatory: false, dispatch: true, instalation: true, can_retire: true, built_in: false, outlet: false, product_type: '', bstock: false, profit_center: false)
    prod_t.families << services
    prod_t.sale_channels << SaleChannel.all
  end 
  puts 'Servicios creados con éxito!'
rescue Exception => e
  puts 'WARNING: Falló la carga de servicios X.X'
end

begin
  if (state_to_delete = QuotationState.find_by(name: 'Envíos por validar'))
    Quotation.joins(:quotation_state)
             .where(quotation_states: {name: 'Envíos por validar'})
             .update_all(quotation_state_id: 19)
    state_to_delete.destroy
  end
  QuotationState.create(id: 20, name: 'Finalizado', stage: 5)
  QuotationState.create(id: 19, name: 'Despachos e Instalaciones', stage: 3)
  QuotationState.create(id: 1, name: 'Enviada', stage: 1)
  QuotationState.create(id: 2, name: 'En curso', stage: 1)
  QuotationState.create(id: 3, name: 'Pendiente', stage: 2)
  QuotationState.create(id: 4, name: 'En preparación', stage: 3)
  QuotationState.create(id: 5, name: 'Cerrado', stage: 5)
  QuotationState.create(id: 6, name: 'Vencida', stage: 5)
  QuotationState.create(id: 7, name: 'Despachado', stage: 3)
  QuotationState.create(id: 8, name: 'Entregado', stage: 5)
  QuotationState.create(id: 9, name: 'Por instalar', stage: 4)
  QuotationState.create(id: 10, name: 'Entrega Pendiente', stage: 3)
  QuotationState.create(id: 11, name: 'Instalado', stage: 5)
  QuotationState.create(id: 12, name: 'Instalación Pendiente', stage: 4)
  QuotationState.create(id: 13, name: 'Por activar', stage: 5)
  QuotationState.create(id: 14, name: 'Productos activados', stage: 5)
  QuotationState.create(id: 15, name: 'Ingresada', stage: 1)
  QuotationState.create(id: 16, name: 'Cancelada', stage: 5)
  QuotationState.create(id: 17, name: 'En Negociación', stage: 1)
  QuotationState.create(id: 18, name: 'Lead', stage: 1)
rescue Exception => e
  puts 'WARNING: Estados de cotizaciones ya creados'
end

begin
  Retail.create(id: 7, name: 'HBT')
  Retail.create(id: 1, name: 'Falabella')
  Retail.create(id: 2, name: 'Linio')
  Retail.create(id: 3, name: 'Travel')
  Retail.create(id: 4, name: 'Paris')
  Retail.create(id: 5, name: 'BCI')
  Retail.create(id: 6, name: 'Itau')
  Retail.create(id: 8, name: 'KITCHENCENTER')
  Retail.create(id: 9, name: 'Paris Marketplace')
  Retail.create(id: 10, name: 'Mercado Libre')
  Retail.create(id: 11, name: 'Falabella Marketplace')
  Retail.create(id: 12, name: 'Ripley Marketplace')
  puts 'Retails creados con éxito!'
rescue Exception => e
  puts 'WARNING: Retails ya creados'
end